"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 08:11:57.442989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_subjects_slug'), 'subjects', ['slug'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('college', sa.String(length=160), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('topics', sa.Text(), nullable=False),
    sa.CheckConstraint('number >= 1 AND number <= 12', name='ck_unit_number'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'subject_id', name='uq_unit_id_subject'),
    sa.UniqueConstraint('subject_id', 'number', name='uq_unit_subject_number')
    )
    op.create_index(op.f('ix_units_subject_id'), 'units', ['subject_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_key', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=32), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('star_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('average_rating', sa.Float(), server_default='0', nullable=False),
    sa.Column('bookmark_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tags_text', sa.Text(), server_default='', nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(tags_text, '')), 'B') || setweight(to_tsvector('english', coalesce(description, '')), 'C')", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("exam_type IS NULL OR exam_type IN ('mid1', 'mid2', 'semester', 'supplementary', 'internal')", name='ck_exam_type'),
    sa.CheckConstraint("resource_type IN ('notes', 'pyq', 'mid', 'semester', 'question_bank', 'assignment', 'reference')", name='ck_resource_type'),
    sa.CheckConstraint('average_rating >= 0 AND average_rating <= 5', name='ck_resource_avg_rating'),
    sa.CheckConstraint('year >= 1990 AND year <= 2100', name='ck_resource_year'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id', 'subject_id'], ['units.id', 'units.subject_id'], name='fk_resource_unit_subject'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_key')
    )
    op.create_index(op.f('ix_resources_created_at'), 'resources', ['created_at'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index('ix_resources_search_vector', 'resources', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_resources_subject_id'), 'resources', ['subject_id'], unique=False)
    op.create_index('ix_resources_subject_unit_type', 'resources', ['subject_id', 'unit_id', 'resource_type'], unique=False)
    op.create_index('ix_resources_title_trgm', 'resources', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index(op.f('ix_resources_unit_id'), 'resources', ['unit_id'], unique=False)
    op.create_index(op.f('ix_resources_uploaded_by'), 'resources', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_resources_year'), 'resources', ['year'], unique=False)
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_id', name='uq_bookmark_user_resource')
    )
    op.create_index(op.f('ix_bookmarks_resource_id'), 'bookmarks', ['resource_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason IN ('spam', 'wrong_subject', 'low_quality', 'copyright', 'inappropriate', 'other')", name='ck_report_reason'),
    sa.CheckConstraint("status IN ('open', 'resolved', 'dismissed')", name='ck_report_status'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_id', name='uq_report_user_resource')
    )
    op.create_index(op.f('ix_reports_resource_id'), 'reports', ['resource_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('resource_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_rating_range'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_id', name='uq_rating_user_resource')
    )
    op.create_index(op.f('ix_resource_ratings_resource_id'), 'resource_ratings', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_ratings_user_id'), 'resource_ratings', ['user_id'], unique=False)
    op.create_table('resource_stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_id', name='uq_star_user_resource')
    )
    op.create_index(op.f('ix_resource_stars_resource_id'), 'resource_stars', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_stars_user_id'), 'resource_stars', ['user_id'], unique=False)
    op.create_table('resource_tags',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'tag_id')
    )
    op.create_table('resource_texts',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(content, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_resource_texts_tsv', 'resource_texts', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('resource_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('last_page', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_views_resource_id'), 'resource_views', ['resource_id'], unique=False)
    op.create_index('ix_views_user_viewed', 'resource_views', ['user_id', 'viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_views_user_viewed', table_name='resource_views')
    op.drop_index(op.f('ix_resource_views_resource_id'), table_name='resource_views')
    op.drop_table('resource_views')
    op.drop_index('ix_resource_texts_tsv', table_name='resource_texts', postgresql_using='gin')
    op.drop_table('resource_texts')
    op.drop_table('resource_tags')
    op.drop_index(op.f('ix_resource_stars_user_id'), table_name='resource_stars')
    op.drop_index(op.f('ix_resource_stars_resource_id'), table_name='resource_stars')
    op.drop_table('resource_stars')
    op.drop_index(op.f('ix_resource_ratings_user_id'), table_name='resource_ratings')
    op.drop_index(op.f('ix_resource_ratings_resource_id'), table_name='resource_ratings')
    op.drop_table('resource_ratings')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_resource_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_resource_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_resources_year'), table_name='resources')
    op.drop_index(op.f('ix_resources_uploaded_by'), table_name='resources')
    op.drop_index(op.f('ix_resources_unit_id'), table_name='resources')
    op.drop_index('ix_resources_title_trgm', table_name='resources', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_resources_subject_unit_type', table_name='resources')
    op.drop_index(op.f('ix_resources_subject_id'), table_name='resources')
    op.drop_index('ix_resources_search_vector', table_name='resources', postgresql_using='gin')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_created_at'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_units_subject_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_subjects_slug'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
