"""document file types

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04 09:20:58.247928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('file_type', sa.String(length=16), server_default='pdf', nullable=False))
    op.add_column('resources', sa.Column('mime_type', sa.String(length=127), server_default='application/pdf', nullable=False))
    op.create_check_constraint(
        'ck_resource_file_type', 'resources',
        "file_type IN ('pdf', 'document', 'presentation', 'spreadsheet', 'text', 'image')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_resource_file_type', 'resources', type_='check')
    op.drop_column('resources', 'mime_type')
    op.drop_column('resources', 'file_type')
    # ### end Alembic commands ###
