"""griet curriculum

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04 09:45:10.361049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('subject_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('elective', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'branch_id', name='uq_offering_subject_branch')
    )
    op.create_index(op.f('ix_subject_offerings_branch_id'), 'subject_offerings', ['branch_id'], unique=False)
    op.create_index(op.f('ix_subject_offerings_subject_id'), 'subject_offerings', ['subject_id'], unique=False)
    op.add_column('subjects', sa.Column('course_code', sa.String(length=16), nullable=True))
    op.add_column('subjects', sa.Column('regulation', sa.String(length=8), nullable=True))
    op.add_column('subjects', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('ltpc', sa.String(length=32), server_default='', nullable=False))
    op.add_column('subjects', sa.Column('credits', sa.Float(), server_default='0', nullable=False))
    op.add_column('subjects', sa.Column('kind', sa.String(length=16), server_default='theory', nullable=False))
    op.add_column('subjects', sa.Column('outcomes', sa.Text(), server_default='', nullable=False))
    op.add_column('subjects', sa.Column('books', sa.Text(), server_default='', nullable=False))
    op.add_column('subjects', sa.Column('lab_tasks', sa.Text(), server_default='', nullable=False))
    op.add_column('subjects', sa.Column('source_url', sa.Text(), server_default='', nullable=False))
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=160),
               existing_nullable=False)
    op.drop_constraint(op.f('subjects_code_key'), 'subjects', type_='unique')
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=False)
    op.create_index(op.f('ix_subjects_regulation'), 'subjects', ['regulation'], unique=False)
    op.create_unique_constraint('uq_subjects_course_code', 'subjects', ['course_code'])
    op.alter_column('units', 'title',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.add_column('users', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('regulation', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('current_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('current_semester', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_users_branch', 'users', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint('ck_subject_year', 'subjects', 'year IS NULL OR (year >= 1 AND year <= 4)')
    op.create_check_constraint('ck_subject_semester', 'subjects', 'semester IS NULL OR semester IN (1, 2)')
    op.create_check_constraint('ck_subject_kind', 'subjects', "kind IN ('theory', 'lab', 'project')")
    # Same lock-down as 0002: unreachable through Supabase's Data API.
    op.execute('ALTER TABLE branches ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE subject_offerings ENABLE ROW LEVEL SECURITY')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_branch', 'users', type_='foreignkey')
    op.drop_column('users', 'current_semester')
    op.drop_column('users', 'current_year')
    op.drop_column('users', 'regulation')
    op.drop_column('users', 'branch_id')
    op.alter_column('units', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
    op.drop_constraint('ck_subject_kind', 'subjects', type_='check')
    op.drop_constraint('ck_subject_semester', 'subjects', type_='check')
    op.drop_constraint('ck_subject_year', 'subjects', type_='check')
    op.drop_constraint('uq_subjects_course_code', 'subjects', type_='unique')
    op.drop_index(op.f('ix_subjects_regulation'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.create_unique_constraint(op.f('subjects_code_key'), 'subjects', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('subjects', 'name',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('subjects', 'source_url')
    op.drop_column('subjects', 'lab_tasks')
    op.drop_column('subjects', 'books')
    op.drop_column('subjects', 'outcomes')
    op.drop_column('subjects', 'kind')
    op.drop_column('subjects', 'credits')
    op.drop_column('subjects', 'ltpc')
    op.drop_column('subjects', 'semester')
    op.drop_column('subjects', 'year')
    op.drop_column('subjects', 'regulation')
    op.drop_column('subjects', 'course_code')
    op.drop_index(op.f('ix_subject_offerings_subject_id'), table_name='subject_offerings')
    op.drop_index(op.f('ix_subject_offerings_branch_id'), table_name='subject_offerings')
    op.drop_table('subject_offerings')
    op.drop_table('branches')
    # ### end Alembic commands ###
