"""Curriculum used to seed realistic subjects, units and generated PDFs."""

SUBJECTS = [
    {
        "code": "DBMS",
        "slug": "dbms",
        "name": "Database Management Systems",
        "aliases": "dbms,database,databases,database management,db",
        "description": "Design, query and manage relational databases — from ER modelling and SQL to normalization, transactions and recovery.",
        "units": [
            ("Introduction & ER Model", [
                ("Database System Architecture", "A DBMS separates the logical view of data from physical storage using a three-schema architecture: external, conceptual and internal levels."),
                ("Data Independence", "Logical data independence lets the conceptual schema change without rewriting applications; physical data independence hides storage changes from the conceptual level."),
                ("Entity-Relationship Model", "ER diagrams model the real world as entities, attributes and relationships, and are the standard first step of database design."),
                ("Cardinality and Participation", "Mapping cardinalities (1:1, 1:N, M:N) and total or partial participation constraints describe how entities relate."),
                ("Weak Entity Sets", "A weak entity has no primary key of its own and is identified through an identifying relationship with its owner entity."),
                ("Keys", "Super keys, candidate keys, primary keys and foreign keys uniquely identify tuples and enforce referential integrity."),
            ]),
            ("Relational Model & SQL", [
                ("Relational Algebra", "Selection, projection, union, set difference, Cartesian product and rename form the procedural query language behind SQL."),
                ("Joins", "Inner, natural, left, right and full outer joins combine tuples from relations based on a join predicate."),
                ("Nested Queries", "Subqueries with IN, EXISTS, ANY and ALL allow a query to use the result of another query, correlated or uncorrelated."),
                ("Aggregate Functions", "COUNT, SUM, AVG, MIN and MAX with GROUP BY and HAVING summarise groups of rows."),
                ("Views", "A view is a virtual relation defined by a query; updatable views must map unambiguously to base tables."),
                ("Integrity Constraints", "NOT NULL, UNIQUE, CHECK, PRIMARY KEY and FOREIGN KEY constraints protect data correctness."),
            ]),
            ("Normalization & Schema Refinement", [
                ("Functional Dependencies", "A functional dependency X -> Y states that tuples agreeing on X must agree on Y; Armstrong's axioms derive all implied dependencies."),
                ("Closure of Attributes", "The attribute closure X+ is used to test candidate keys and to check whether a dependency is implied."),
                ("First, Second and Third Normal Form", "1NF requires atomic values, 2NF removes partial dependencies on a key and 3NF removes transitive dependencies."),
                ("Boyce-Codd Normal Form", "BCNF requires every determinant to be a super key; it is stricter than 3NF and may not preserve dependencies."),
                ("Lossless Join Decomposition", "A decomposition is lossless if the natural join of the parts reproduces the original relation exactly."),
                ("Multivalued Dependencies and 4NF", "Multivalued dependencies capture independent multi-valued facts; 4NF eliminates non-trivial MVDs."),
            ]),
            ("Transactions & Concurrency Control", [
                ("ACID Properties", "Atomicity, consistency, isolation and durability define correct transaction behaviour."),
                ("Serializability", "A schedule is conflict serializable if its precedence graph is acyclic, making it equivalent to some serial order."),
                ("Two-Phase Locking", "2PL has a growing and a shrinking phase; strict 2PL holds exclusive locks until commit to avoid cascading aborts."),
                ("Timestamp Ordering", "Timestamp protocols order conflicting operations by transaction timestamps, with Thomas' write rule skipping obsolete writes."),
                ("Deadlock Handling in Databases", "Wait-die and wound-wait schemes prevent deadlocks, while wait-for graphs detect them."),
                ("Isolation Levels", "Read uncommitted, read committed, repeatable read and serializable trade consistency for concurrency."),
            ]),
            ("Storage, Indexing & Recovery", [
                ("File Organization", "Heap, sequential and hashed file organizations determine how records are placed on disk blocks."),
                ("B+ Tree Indexes", "B+ trees keep data in sorted leaf nodes linked together, giving logarithmic search and efficient range scans."),
                ("Hash Indexes", "Static and extendible hashing map search keys to buckets for constant-time equality lookups."),
                ("Log-Based Recovery", "Write-ahead logging records undo and redo information so committed work survives crashes."),
                ("Checkpoints", "Checkpoints bound the amount of log that must be scanned during recovery."),
                ("ARIES", "ARIES recovery runs analysis, redo and undo passes using log sequence numbers and compensation log records."),
            ]),
        ],
    },
    {
        "code": "DS",
        "slug": "data-structures",
        "name": "Data Structures",
        "aliases": "ds,dsa,data structure,data structures and algorithms",
        "description": "Core data structures and the algorithms built on them — arrays, lists, stacks, trees, graphs, sorting and hashing.",
        "units": [
            ("Arrays, Linked Lists & Complexity", [
                ("Asymptotic Notation", "Big-O, Omega and Theta describe upper, lower and tight bounds on an algorithm's growth rate."),
                ("Arrays", "Arrays store elements contiguously, giving O(1) indexed access but O(n) insertion in the middle."),
                ("Singly Linked Lists", "Each node stores data and a pointer to the next node, allowing O(1) insertion at the head."),
                ("Doubly and Circular Linked Lists", "Doubly linked lists keep prev and next pointers; circular lists link the tail back to the head."),
                ("Sparse Matrices", "Sparse matrices store only non-zero entries using triplet or linked representations."),
                ("Polynomial Representation", "Linked lists represent polynomials as sequences of coefficient-exponent terms for addition and multiplication."),
            ]),
            ("Stacks & Queues", [
                ("Stack ADT", "A stack is a LIFO structure supporting push, pop and peek in constant time."),
                ("Infix to Postfix Conversion", "Operator precedence and a stack convert infix expressions to postfix for easy evaluation."),
                ("Recursion and the Call Stack", "Each recursive call pushes a frame; tail recursion can be converted to iteration."),
                ("Queue ADT", "A queue is FIFO; circular arrays avoid wasting space after dequeues."),
                ("Deque and Priority Queue", "Deques allow insertion and deletion at both ends; priority queues serve the highest-priority element first."),
                ("Applications of Stacks and Queues", "Balanced parentheses, undo operations, BFS and CPU scheduling all rely on stacks or queues."),
            ]),
            ("Trees & Binary Search Trees", [
                ("Binary Tree Traversals", "Inorder, preorder, postorder and level-order traversals visit every node in a defined order."),
                ("Binary Search Trees", "In a BST every left descendant is smaller and every right descendant larger, enabling O(h) search."),
                ("AVL Trees", "AVL trees keep balance factors in {-1, 0, 1} using LL, RR, LR and RL rotations."),
                ("Heaps", "A binary heap is a complete tree satisfying the heap property, used for heapsort and priority queues."),
                ("B-Trees", "B-trees are balanced multiway search trees designed to minimise disk accesses."),
                ("Threaded Binary Trees", "Threads replace null pointers with links to inorder predecessors or successors."),
            ]),
            ("Graphs & Graph Algorithms", [
                ("Graph Representations", "Adjacency matrices use O(V^2) space while adjacency lists use O(V + E)."),
                ("Breadth-First Search", "BFS explores level by level using a queue and finds shortest paths in unweighted graphs."),
                ("Depth-First Search", "DFS explores as deep as possible using recursion or a stack and underlies topological sort."),
                ("Minimum Spanning Trees", "Prim's and Kruskal's algorithms find a spanning tree of minimum total weight."),
                ("Dijkstra's Algorithm", "Dijkstra computes single-source shortest paths for non-negative edge weights using a priority queue."),
                ("Topological Sorting", "A topological order of a DAG lists each vertex before all vertices it points to."),
            ]),
            ("Sorting, Searching & Hashing", [
                ("Binary Search", "Binary search halves a sorted range each step, running in O(log n)."),
                ("Quick Sort", "Quick sort partitions around a pivot; average O(n log n), worst case O(n^2)."),
                ("Merge Sort", "Merge sort divides the array, sorts halves recursively and merges them in O(n log n)."),
                ("Heap Sort", "Heap sort builds a max-heap and repeatedly extracts the maximum in O(n log n) time."),
                ("Hash Functions", "Division, multiplication and universal hashing map keys to table indices."),
                ("Collision Resolution", "Chaining, linear probing, quadratic probing and double hashing resolve hash collisions."),
            ]),
        ],
    },
    {
        "code": "OS",
        "slug": "operating-systems",
        "name": "Operating Systems",
        "aliases": "os,operating system,operating systems",
        "description": "How operating systems manage processes, CPU time, memory, storage and devices — and keep it all safe and concurrent.",
        "units": [
            ("Introduction & Process Management", [
                ("Operating System Structures", "Monolithic, layered, microkernel and modular designs trade performance for isolation."),
                ("System Calls", "System calls are the interface through which user programs request kernel services."),
                ("Process Concept", "A process is a program in execution with its own PCB, address space and state."),
                ("Process States", "Processes move between new, ready, running, waiting and terminated states."),
                ("Context Switching", "The kernel saves and restores PCB state to switch the CPU between processes."),
                ("Threads", "Threads share a process's address space; user-level and kernel-level threads map via many-to-one, one-to-one or many-to-many models."),
            ]),
            ("CPU Scheduling & Synchronization", [
                ("Scheduling Criteria", "CPU utilisation, throughput, turnaround time, waiting time and response time evaluate schedulers."),
                ("FCFS, SJF and Round Robin", "FCFS is simple but suffers convoy effects; SJF minimises average waiting time; round robin uses time quanta."),
                ("Priority Scheduling", "Priority scheduling can starve low-priority processes, which aging solves."),
                ("Critical Section Problem", "Solutions must provide mutual exclusion, progress and bounded waiting."),
                ("Semaphores", "Counting and binary semaphores coordinate processes using wait and signal operations."),
                ("Classic Synchronization Problems", "Producer-consumer, readers-writers and dining philosophers model common concurrency patterns."),
            ]),
            ("Deadlocks", [
                ("Deadlock Characterization", "Deadlock requires mutual exclusion, hold and wait, no preemption and circular wait simultaneously."),
                ("Resource Allocation Graph", "A cycle in a single-instance resource allocation graph implies deadlock."),
                ("Deadlock Prevention", "Prevention denies at least one of the four necessary conditions, e.g. by ordering resources."),
                ("Deadlock Avoidance", "Avoidance keeps the system in a safe state by checking each request before granting it."),
                ("Banker's Algorithm", "The Banker's algorithm uses Available, Max, Allocation and Need matrices to find a safe sequence."),
                ("Deadlock Detection and Recovery", "Detection algorithms find deadlocked processes; recovery terminates processes or preempts resources."),
            ]),
            ("Memory Management & Virtual Memory", [
                ("Contiguous Allocation", "First fit, best fit and worst fit allocate memory partitions, causing external fragmentation."),
                ("Paging", "Paging divides memory into fixed-size frames and uses page tables to translate addresses."),
                ("Translation Lookaside Buffer", "The TLB caches page table entries to make address translation fast."),
                ("Segmentation", "Segmentation divides a program into logical segments such as code, stack and heap."),
                ("Demand Paging", "Pages are loaded only when referenced, triggering page faults otherwise."),
                ("Page Replacement Algorithms", "FIFO, optimal and LRU choose victim pages; FIFO can exhibit Belady's anomaly."),
            ]),
            ("File Systems & I/O", [
                ("File Concepts", "Files have attributes, operations and access methods such as sequential and direct access."),
                ("Directory Structures", "Single-level, two-level, tree and acyclic-graph directories organise files."),
                ("Allocation Methods", "Contiguous, linked and indexed allocation trade fragmentation against access speed."),
                ("Free Space Management", "Bit vectors, linked lists and grouping track free disk blocks."),
                ("Disk Scheduling", "FCFS, SSTF, SCAN, C-SCAN and LOOK order disk requests to reduce seek time."),
                ("RAID", "RAID levels combine disks for performance and redundancy using striping, mirroring and parity."),
            ]),
        ],
    },
    {
        "code": "CN",
        "slug": "computer-networks",
        "name": "Computer Networks",
        "aliases": "cn,networks,networking,computer network,computer networks",
        "description": "From bits on the wire to HTTP — layered network architectures, routing, transport protocols and the applications on top.",
        "units": [
            ("Introduction & Physical Layer", [
                ("OSI Reference Model", "The OSI model has seven layers: physical, data link, network, transport, session, presentation and application."),
                ("TCP/IP Model", "The TCP/IP stack collapses OSI into link, internet, transport and application layers."),
                ("Network Topologies", "Bus, star, ring, mesh and hybrid topologies differ in cost, fault tolerance and performance."),
                ("Transmission Media", "Twisted pair, coaxial cable, optical fibre and wireless media carry signals with different bandwidths."),
                ("Multiplexing", "FDM, TDM and WDM share a single channel among multiple signals."),
                ("Switching Techniques", "Circuit switching reserves a path; packet switching forwards independent packets."),
            ]),
            ("Data Link Layer & MAC", [
                ("Framing", "Character count, byte stuffing and bit stuffing mark frame boundaries."),
                ("Error Detection", "Parity, checksums and CRC detect transmission errors."),
                ("Hamming Code", "Hamming codes add parity bits that can locate and correct single-bit errors."),
                ("Sliding Window Protocols", "Stop-and-wait, Go-Back-N and Selective Repeat provide reliable, flow-controlled delivery."),
                ("ALOHA and CSMA/CD", "Pure and slotted ALOHA and CSMA/CD govern access to a shared medium."),
                ("Ethernet and Switching", "Ethernet frames carry MAC addresses; learning switches build forwarding tables."),
            ]),
            ("Network Layer & Routing", [
                ("IPv4 Addressing", "IPv4 addresses are 32-bit, organised into classes or CIDR blocks."),
                ("Subnetting", "Subnet masks split an address block into smaller networks for efficient allocation."),
                ("Distance Vector Routing", "Routers share distance vectors with neighbours using the Bellman-Ford equation; count-to-infinity is a known issue."),
                ("Link State Routing", "Each router floods link-state advertisements and runs Dijkstra's algorithm (OSPF)."),
                ("IPv6", "IPv6 uses 128-bit addresses, a simplified header and extension headers."),
                ("ICMP, ARP and NAT", "ICMP reports errors, ARP resolves IP to MAC addresses and NAT maps private to public addresses."),
            ]),
            ("Transport Layer (TCP/UDP)", [
                ("UDP", "UDP is a connectionless, best-effort transport with minimal header overhead."),
                ("TCP Connection Management", "TCP opens connections with a three-way handshake and closes them with a four-way exchange."),
                ("TCP Flow Control", "The receive window prevents a fast sender from overwhelming a slow receiver."),
                ("TCP Congestion Control", "Slow start, congestion avoidance, fast retransmit and fast recovery adapt the congestion window."),
                ("Port Numbers and Sockets", "Ports multiplex transport connections; sockets are endpoints identified by IP and port."),
                ("Quality of Service", "Leaky bucket and token bucket algorithms shape traffic to meet QoS goals."),
            ]),
            ("Application Layer & Security", [
                ("DNS", "DNS resolves domain names via a hierarchy of root, TLD and authoritative servers."),
                ("HTTP", "HTTP is a stateless request-response protocol; persistent connections and caching improve performance."),
                ("Email Protocols", "SMTP sends mail while POP3 and IMAP retrieve it."),
                ("Symmetric and Public Key Cryptography", "DES and AES use shared keys; RSA uses public/private key pairs."),
                ("Digital Signatures", "Digital signatures provide authentication, integrity and non-repudiation."),
                ("Firewalls", "Packet-filtering and application-level firewalls enforce network security policies."),
            ]),
        ],
    },
    {
        "code": "MATH",
        "slug": "mathematics",
        "name": "Mathematics",
        "aliases": "maths,math,mathematics,engineering mathematics,discrete maths,discrete mathematics,m1,m2",
        "description": "Engineering and discrete mathematics — linear algebra, calculus, probability, logic and graph theory for computer science.",
        "units": [
            ("Matrices & Linear Algebra", [
                ("Rank of a Matrix", "The rank is the number of linearly independent rows, found by reducing to echelon form."),
                ("Systems of Linear Equations", "Consistency of AX = B is decided by comparing the ranks of A and the augmented matrix."),
                ("Eigenvalues and Eigenvectors", "Eigenvalues solve det(A - lambda I) = 0; eigenvectors span the corresponding null spaces."),
                ("Cayley-Hamilton Theorem", "Every square matrix satisfies its own characteristic equation, which helps compute inverses and powers."),
                ("Diagonalization", "A matrix with n independent eigenvectors can be written as P D P^-1."),
                ("Quadratic Forms", "Quadratic forms are classified as positive definite, negative definite or indefinite using eigenvalues."),
            ]),
            ("Differential Calculus", [
                ("Mean Value Theorems", "Rolle's, Lagrange's and Cauchy's mean value theorems relate derivatives to function values."),
                ("Taylor and Maclaurin Series", "Taylor series expand a function as a power series around a point."),
                ("Partial Derivatives", "Partial derivatives measure change with respect to one variable while others are fixed."),
                ("Jacobians", "The Jacobian determinant measures how a transformation scales area or volume."),
                ("Maxima and Minima", "Critical points of multivariable functions are classified using the second derivative test."),
                ("Lagrange Multipliers", "Lagrange's method finds extrema of a function subject to equality constraints."),
            ]),
            ("Probability & Statistics", [
                ("Conditional Probability", "P(A|B) = P(A and B) / P(B) gives the probability of A given B occurred."),
                ("Bayes' Theorem", "Bayes' theorem updates prior probabilities using observed evidence."),
                ("Random Variables", "Discrete and continuous random variables are described by PMFs, PDFs and CDFs."),
                ("Binomial and Poisson Distributions", "Binomial models successes in n trials; Poisson approximates rare events."),
                ("Normal Distribution", "The normal distribution is symmetric about its mean; z-scores standardise values."),
                ("Correlation and Regression", "Karl Pearson's coefficient measures linear correlation; regression lines predict one variable from another."),
            ]),
            ("Discrete Mathematics & Logic", [
                ("Propositional Logic", "Propositions combine with connectives; truth tables test tautologies and contradictions."),
                ("Predicate Logic", "Quantifiers for all and there exists extend propositional logic to statements about objects."),
                ("Rules of Inference", "Modus ponens, modus tollens and resolution derive valid conclusions."),
                ("Set Theory and Relations", "Relations can be reflexive, symmetric, antisymmetric and transitive; equivalence relations partition sets."),
                ("Functions", "Functions may be injective, surjective or bijective; bijections have inverses."),
                ("Mathematical Induction", "Induction proves a statement for all natural numbers via a base case and an inductive step."),
            ]),
            ("Graph Theory & Combinatorics", [
                ("Permutations and Combinations", "nPr counts ordered arrangements and nCr counts unordered selections."),
                ("Pigeonhole Principle", "If n + 1 objects go into n boxes, some box holds at least two objects."),
                ("Recurrence Relations", "Linear recurrences are solved with characteristic equations or generating functions."),
                ("Euler and Hamiltonian Paths", "Euler paths traverse every edge once; Hamiltonian paths visit every vertex once."),
                ("Graph Colouring", "The chromatic number is the minimum colours needed so adjacent vertices differ."),
                ("Planar Graphs", "Euler's formula V - E + F = 2 holds for connected planar graphs."),
            ]),
        ],
    },
]

NAMED_USERS = [
    # username, full name, college
    ("sanjith", "Sanjith Kumar", "JNTU Hyderabad"),
    ("priya", "Priya Sharma", "JNTU Hyderabad"),
    ("arjun", "Arjun Reddy", "Osmania University"),
    ("meera", "Meera Nair", "VIT Vellore"),
    ("rahul", "Rahul Verma", "JNTU Hyderabad"),
    ("kavya", "Kavya Iyer", "Anna University"),
    ("aditya", "Aditya Singh", "IIIT Hyderabad"),
]

FIRST_NAMES = [
    "ananya", "rohan", "sneha", "vikram", "divya", "karthik", "neha", "siddharth", "pooja", "varun",
    "ishita", "nikhil", "shreya", "harsha", "tanvi", "manoj", "riya", "abhishek", "lakshmi", "yash",
]
